# Generated by Django 4.2.2 on 2023-08-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_discription', models.CharField(max_length=100)),
                ('product_price', models.CharField(max_length=100)),
                ('product_offerprice', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
