# Generated by Django 4.2.2 on 2023-08-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproduct',
            old_name='product_discription',
            new_name='product_description',
        ),
    ]
