# Generated by Django 4.2.2 on 2023-08-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_product_discription_addproduct_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producti_id', models.CharField(max_length=100)),
                ('producti_name', models.CharField(max_length=100)),
                ('producti_price', models.CharField(max_length=100)),
                ('producti_category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=100)),
                ('producti_qty', models.CharField(max_length=100)),
                ('totalprice', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
