# Generated by Django 4.2.2 on 2023-09-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_addcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('totalprice', models.CharField(max_length=100)),
            ],
        ),
    ]
