# Generated by Django 4.2.2 on 2023-09-07 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='totalprice',
            new_name='amount',
        ),
    ]
