# Generated by Django 5.2.4 on 2025-12-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcart',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterModelTable(
            name='addcart',
            table='Addcart',
        ),
        migrations.AlterModelTable(
            name='addproduct',
            table='Addproduct',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='Payment',
        ),
        migrations.AlterModelTable(
            name='wishlist',
            table='Wishlist',
        ),
    ]
